/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_liveneeq_ffmpegexample_MainActivity */

#ifndef _Included_com_liveneeq_ffmpegexample_MainActivity
#define _Included_com_liveneeq_ffmpegexample_MainActivity
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_liveneeq_ffmpegexample_MainActivity
 * Method:    getffmpegFromJNI
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_liveneeq_ffmpegexample_MainActivity_getffmpegFromJNI
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
